<a href="https://colab.research.google.com/github/JudithVillaseca/unidad1/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy es una libreria de Python.
Numpy se utiliza para trabajar con matrices o arreglos
Numpy es la abreviatura de "Python numerico"
Tambien tiene funciones para trabajar en el dominio del algebra lineal, la transformada y las matrices
En Python tenemos listas que sirven como matrices pero son lentas de procesar. Numpy tiene como objetivo proporcionar un objeto de matriz que sea 50 veces mas rapido que las listas tradicionales.

In [1]:
#Primero tenemos que importar la libreria
import numpy

arreglo=numpy.array([1,2,3,4,5])
print(arreglo)


[1 2 3 4 5]


Numpy como np
Numpy generalmente se importa bajo alias np. En python los alias son un nombre alternativo para referirse a la misma cosa

In [2]:
import numpy as np

arreglo=np.array([6,7,8,9,10])
print(arreglo)

[ 6  7  8  9 10]


Comprobando la version de Numpy
La cadena de la version se almacena en el atributo __version__

In [3]:
import numpy as np

print(np.__version__)

2.0.2


Numpy creando matrices
Crear un objeto ndarray de Numpy
NUmpy se utiliza para trabajar con matrices. El objeto de matriz se llama ndarray.
Podemos crear un numpy ndarray utilizando la funcion array()

In [4]:
import numpy as np

arreglo=np.array(["Raul", "Ana", "Kimberly", "Yazmin"])
print(arreglo)
print(type(arreglo))

['Raul' 'Ana' 'Kimberly' 'Yazmin']
<class 'numpy.ndarray'>


Dimensiones en matrices
Una dimension en matrices es un nivel de profundidad de matriz (matrices anidadas)
Una matriz anidada contiene matrices como elementos
Matrices 0-D. Son elemntos de una matriz. Cada valor de una matriz es una matriz 0-D. Ejemplo: Crea una matriz 0-D con un valor de 42

In [5]:
import numpy as np

arreglo=np.array(42)

print(arreglo)

42


Matrices 1-D
Una matriz que tiene matrices 0-D como elementos se denomina matriz unidimensional o 1-D.
Estas son las matrices mas comunes y basicas.
Ejemplo: Crea una matriz de 1-D que tenga los valores 1,2,3,4,5

In [6]:
import numpy as np

arreglo=np.array([1,2,3,4,5])

print(arreglo)


[1 2 3 4 5]


Matrices 2D
Una matriz que tiene matrices 1-D como elementos se denomina matriz 2D.
A menudo se utilizan para representar matrices de segundo orden. NUmpy tiene un submodulo completo dedicado a operaciones con matrices llamado numpy.mat.
Ejemplo: Crea una matriz de 2D que contenga dos matrices con los valores 123 y 456.

In [7]:
import numpy as np

arreglo=np.array([[1,2,3],[4,5,6]])

print(arreglo)

[[1 2 3]
 [4 5 6]]


Matrices 3D
Una matriz que tiene matrices 2D se denomina matriz 3D.
Estas matrices se utilizan para representar una matriz de tercer orden.
Ejemplo: Crea una matriz 3D con dos matrices bidimensionales, ambas conteniendo dos matrices con los valores 1,2,3 y 4,5,6.

In [9]:
import numpy as np

arreglo=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(arreglo)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
