<a href="https://colab.research.google.com/github/JudithVillaseca/unidad1/blob/main/Practica7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Judith Villaseca Sanchez - Practica 7
25 de Septiembre del 2025.
-----------------------------
Slincing Numpy
--------------------------
Utilice STEP para determinar el paso del corte:
Ejemplo: ([1,2,3,4,5,7]) - Devuelve todos los elementos del indice 1 al indice 5


In [1]:
import numpy as np
arreglo=np.array([1,2,3,4,5,6,7])
print(arreglo[1:5:2])


[2 4]


Ejemplo 2: ([1,2,3,4,5,6,7])
Devuelve los  elementos de la matriz
--------------------------------------


In [3]:
import numpy as np
arreglo=np.array([1,2,3,4,5,6,7])
print(arreglo[::2])

[1 3 5 7]


SLice de matrices 2D
---------------------
Ejemplo: ([[1,2,3,4,5], [6,7,8,9,10]])
Del segundo elemento, corte del indice 1 al indice 4

In [6]:
import numpy as np
arreglo=np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arreglo[1, 1:4])

[7 8 9]


 Ejemplo 4: ([[1,2,3,4,5], [[6,7,8,9,10]])
 De ambos elementos, devuelve el indice 2
 -----------------------------


In [8]:
import numpy as np
arreglo=np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arreglo[0:2, 2])

[3 8]


Ejemplo 5: ([[1,2,3,4,5], [6,7,8,9,10]])
De ambos elementos corta el indice 1 al indice 4.

In [10]:
import numpy as np
arreglo=np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arreglo[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


Ejercicio 1 - Autonomo
Del siguiente arreglo, ¿cual es el resultado?
([1,2,3,4,5,6,7])
Corta del 1er elemento al 6to elemento con paso 2

In [12]:
import numpy as np
arreglo=np.array([1,2,3,4,5,6,7])
print(arreglo[0:6:2])

[1 3 5]
